name = "Форпост"
author = "Vadim"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e768b7b221216ceda0b71aa36ac861f391f6249401d779ff984fd838a1138f7"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
