name = "Форпост"
author = "Vadim"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d3fd36ab261266b30b8152e81e28c76bd39718cb0ffec422d22f23cf1c0083e"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
