name = "Форпост"
author = "Vadim"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "398de6ad971e88256f4e5583ba0ddefe835e39c42dfa1308b89d1b7cabb8a87a"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
